<?php
/**
 * Slider - Shortcode Options
 */
add_action( 'init', 'slider_vc_map' );
if ( ! function_exists( 'slider_vc_map' ) ) {
  function slider_vc_map() {
    vc_map( array(
    "name" => __( "Slider", 'fawzi-core'),
    "base" => "fawzi_slider",
    "description" => __( "Slider Style", 'fawzi-core'),
    "icon" => "fa fa-sliders color-pink",
    "category" => FawziLib::fwzi_cat_name(),
    "params" => array(       

      // List
      array(
        'type' => 'param_group', 
        'value' => '',
        'heading' => __( 'Slider', 'fawzi-core' ),
        'param_name' => 'sliders',
        // Note params is mapped inside param-group:
        'params' => array(      
          array(
            'type' => 'attach_image',
            'value' => '',
            'heading' => __( 'Upload Background Image', 'fawzi-core' ),
            'param_name' => 'slider_image',
            'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Caption Alignment', 'fawzi-core' ),
            'value' => array(
              __( 'Select The Alignment', 'fawzi-core' ) => '',
              __( 'Left', 'fawzi-core' ) => 'left',
              __( 'Right', 'fawzi-core' ) => 'right',
              __( 'Center', 'fawzi-core' ) => 'center',
            ),
            'param_name' => 'caption_alignment',
            'description' => __( 'Select your alignment.', 'fawzi-core' ),
            'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
          ),            
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Slider Title', 'fawzi-core' ),
            'admin_label' => true,
            'param_name' => 'slider_title',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Title Animation', 'fawzi-core' ),
            'value' => array(
              __( 'fadeInDown', 'fawzi-core' )          => 'fadeInDown',
              __( 'bounce', 'fawzi-core' )              => 'bounce',
              __( 'flash', 'fawzi-core' )               => 'flash',
              __( 'pulse', 'fawzi-core' )               => 'pulse',
              __( 'rubberBand', 'fawzi-core' )          => 'rubberBand',
              __( 'shake', 'fawzi-core' )               => 'shake',
              __( 'swing', 'fawzi-core' )               => 'swing',
              __( 'tada', 'fawzi-core' )                => 'tada',
              __( 'wobble', 'fawzi-core' )              => 'wobble',
              __( 'jello', 'fawzi-core' )               => 'jello',
              __( 'bounceIn', 'fawzi-core' )            => 'bounceIn',
              __( 'bounceInDown', 'fawzi-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'fawzi-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'fawzi-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'fawzi-core' )          => 'bounceInUp',
              __( 'bounceOut', 'fawzi-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'fawzi-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'fawzi-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'fawzi-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'fawzi-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'fawzi-core' )              => 'fadeIn',
              __( 'fadeInDownBig', 'fawzi-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'fawzi-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'fawzi-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'fawzi-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'fawzi-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'fawzi-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'fawzi-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'fawzi-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'fawzi-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'fawzi-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'fawzi-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'fawzi-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'fawzi-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'fawzi-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'fawzi-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'fawzi-core' )        => 'fadeOutUpBig',
              __( 'flip', 'fawzi-core' )                => 'flip',
              __( 'flipInX', 'fawzi-core' )             => 'flipInX',
              __( 'flipInY', 'fawzi-core' )             => 'flipInY',
              __( 'flipOutX', 'fawzi-core' )            => 'flipOutX',
              __( 'flipOutY', 'fawzi-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'fawzi-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'fawzi-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'fawzi-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'fawzi-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'fawzi-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'fawzi-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'fawzi-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'fawzi-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'fawzi-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'fawzi-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'fawzi-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'fawzi-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'fawzi-core' )           => 'slideInUp',
              __( 'slideInDown', 'fawzi-core' )         => 'slideInDown',
              __( 'slideInLeft', 'fawzi-core' )         => 'slideInLeft',
              __( 'slideInRight', 'fawzi-core' )        => 'slideInRight',
              __( 'slideOutUp', 'fawzi-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'fawzi-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'fawzi-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'fawzi-core' )       => 'slideOutRight',
              __( 'zoomIn', 'fawzi-core' )              => 'zoomIn',
              __( 'zoomInDown', 'fawzi-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'fawzi-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'fawzi-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'fawzi-core' )            => 'zoomInUp',
              __( 'zoomOut', 'fawzi-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'fawzi-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'fawzi-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'fawzi-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'fawzi-core' )           => 'zoomOutUp',
              __( 'hinge', 'fawzi-core' )               => 'hinge',
              __( 'jackInTheBox', 'fawzi-core' )        => 'jackInTheBox',
              __( 'rollIn', 'fawzi-core' )              => 'rollIn',
              __( 'rollOut', 'fawzi-core' )             => 'rollOut',
            ),
            'param_name' => 'title_animation',
            'description' => __( 'Select your animation.', 'fawzi-core' ),
          ),  
          array(
            'type' => 'textarea',
            'value' => '',
            'heading' => __( 'Slider Content', 'fawzi-core' ),
            'param_name' => 'slider_content',
          ),        
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button One Text', 'fawzi-core' ),
            'param_name' => 'slider_bone_text',
          ), 
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button One Link', 'fawzi-core' ),
            'param_name' => 'slider_bone_link',
          ), 
          array(
            'type' => 'dropdown',
            'heading' => __( 'Button One Animation', 'fawzi-core' ),
            'value' => array(
              __( 'fadeInDown', 'fawzi-core' )          => 'fadeInDown',
              __( 'bounce', 'fawzi-core' )              => 'bounce',
              __( 'flash', 'fawzi-core' )               => 'flash',
              __( 'pulse', 'fawzi-core' )               => 'pulse',
              __( 'rubberBand', 'fawzi-core' )          => 'rubberBand',
              __( 'shake', 'fawzi-core' )               => 'shake',
              __( 'swing', 'fawzi-core' )               => 'swing',
              __( 'tada', 'fawzi-core' )                => 'tada',
              __( 'wobble', 'fawzi-core' )              => 'wobble',
              __( 'jello', 'fawzi-core' )               => 'jello',
              __( 'bounceIn', 'fawzi-core' )            => 'bounceIn',
              __( 'bounceInDown', 'fawzi-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'fawzi-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'fawzi-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'fawzi-core' )          => 'bounceInUp',
              __( 'bounceOut', 'fawzi-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'fawzi-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'fawzi-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'fawzi-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'fawzi-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'fawzi-core' )              => 'fadeIn',
              __( 'fadeInDownBig', 'fawzi-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'fawzi-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'fawzi-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'fawzi-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'fawzi-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'fawzi-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'fawzi-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'fawzi-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'fawzi-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'fawzi-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'fawzi-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'fawzi-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'fawzi-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'fawzi-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'fawzi-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'fawzi-core' )        => 'fadeOutUpBig',
              __( 'flip', 'fawzi-core' )                => 'flip',
              __( 'flipInX', 'fawzi-core' )             => 'flipInX',
              __( 'flipInY', 'fawzi-core' )             => 'flipInY',
              __( 'flipOutX', 'fawzi-core' )            => 'flipOutX',
              __( 'flipOutY', 'fawzi-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'fawzi-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'fawzi-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'fawzi-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'fawzi-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'fawzi-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'fawzi-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'fawzi-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'fawzi-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'fawzi-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'fawzi-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'fawzi-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'fawzi-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'fawzi-core' )           => 'slideInUp',
              __( 'slideInDown', 'fawzi-core' )         => 'slideInDown',
              __( 'slideInLeft', 'fawzi-core' )         => 'slideInLeft',
              __( 'slideInRight', 'fawzi-core' )        => 'slideInRight',
              __( 'slideOutUp', 'fawzi-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'fawzi-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'fawzi-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'fawzi-core' )       => 'slideOutRight',
              __( 'zoomIn', 'fawzi-core' )              => 'zoomIn',
              __( 'zoomInDown', 'fawzi-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'fawzi-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'fawzi-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'fawzi-core' )            => 'zoomInUp',
              __( 'zoomOut', 'fawzi-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'fawzi-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'fawzi-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'fawzi-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'fawzi-core' )           => 'zoomOutUp',
              __( 'hinge', 'fawzi-core' )               => 'hinge',
              __( 'jackInTheBox', 'fawzi-core' )        => 'jackInTheBox',
              __( 'rollIn', 'fawzi-core' )              => 'rollIn',
              __( 'rollOut', 'fawzi-core' )             => 'rollOut',
            ),
            'param_name' => 'bone_animation',
            'description' => __( 'Select your animation.', 'fawzi-core' ),
          ), 
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button Two Text', 'fawzi-core' ),
            'param_name' => 'slider_btwo_text',
          ), 
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Button Two Link', 'fawzi-core' ),
            'param_name' => 'slider_btwo_link',
          ),
          array(
            'type' => 'dropdown',
            'heading' => __( 'Button Two Animation', 'fawzi-core' ),
            'value' => array(
              __( 'fadeInDown', 'fawzi-core' )          => 'fadeInDown',
              __( 'bounce', 'fawzi-core' )              => 'bounce',
              __( 'flash', 'fawzi-core' )               => 'flash',
              __( 'pulse', 'fawzi-core' )               => 'pulse',
              __( 'rubberBand', 'fawzi-core' )          => 'rubberBand',
              __( 'shake', 'fawzi-core' )               => 'shake',
              __( 'swing', 'fawzi-core' )               => 'swing',
              __( 'tada', 'fawzi-core' )                => 'tada',
              __( 'wobble', 'fawzi-core' )              => 'wobble',
              __( 'jello', 'fawzi-core' )               => 'jello',
              __( 'bounceIn', 'fawzi-core' )            => 'bounceIn',
              __( 'bounceInDown', 'fawzi-core' )        => 'bounceInDown',
              __( 'bounceInLeft', 'fawzi-core' )        => 'bounceInLeft',
              __( 'bounceInRight', 'fawzi-core' )       => 'bounceInRight',
              __( 'bounceInUp', 'fawzi-core' )          => 'bounceInUp',
              __( 'bounceOut', 'fawzi-core' )           => 'bounceOut',
              __( 'bounceOutDown', 'fawzi-core' )       => 'bounceOutDown',
              __( 'bounceOutLeft', 'fawzi-core' )       => 'bounceOutLeft',
              __( 'bounceOutRight', 'fawzi-core' )      => 'bounceOutRight',
              __( 'bounceOutUp', 'fawzi-core' )         => 'bounceOutUp',
              __( 'fadeIn', 'fawzi-core' )              => 'fadeIn',              
              __( 'fadeInDownBig', 'fawzi-core' )       => 'fadeInDownBig',
              __( 'fadeInLeft', 'fawzi-core' )          => 'fadeInLeft',
              __( 'fadeInLeftBig', 'fawzi-core' )       => 'fadeInLeftBig',
              __( 'fadeInRight', 'fawzi-core' )         => 'fadeInRight',
              __( 'fadeInRightBig', 'fawzi-core' )      => 'fadeInRightBig',
              __( 'fadeInUp', 'fawzi-core' )            => 'fadeInUp',
              __( 'fadeInUpBig', 'fawzi-core' )         => 'fadeInUpBig',
              __( 'fadeOut', 'fawzi-core' )             => 'fadeOut',
              __( 'fadeOutDown', 'fawzi-core' )         => 'fadeOutDown',
              __( 'fadeOutDownBig', 'fawzi-core' )      => 'fadeOutDownBig',
              __( 'fadeOutLeft', 'fawzi-core' )         => 'fadeOutLeft',
              __( 'fadeOutLeftBig', 'fawzi-core' )      => 'fadeOutLeftBig',
              __( 'fadeOutRight', 'fawzi-core' )        => 'fadeOutRight',
              __( 'fadeOutRightBig', 'fawzi-core' )     => 'fadeOutRightBig',
              __( 'fadeOutUp', 'fawzi-core' )           => 'fadeOutUp',
              __( 'fadeOutUpBig', 'fawzi-core' )        => 'fadeOutUpBig',
              __( 'flip', 'fawzi-core' )                => 'flip',
              __( 'flipInX', 'fawzi-core' )             => 'flipInX',
              __( 'flipInY', 'fawzi-core' )             => 'flipInY',
              __( 'flipOutX', 'fawzi-core' )            => 'flipOutX',
              __( 'flipOutY', 'fawzi-core' )            => 'flipOutY',
              __( 'lightSpeedIn', 'fawzi-core' )        => 'lightSpeedIn',
              __( 'lightSpeedOut', 'fawzi-core' )       => 'lightSpeedOut',
              __( 'rotateIn', 'fawzi-core' )            => 'rotateIn',
              __( 'rotateInDownLeft', 'fawzi-core' )    => 'rotateInDownLeft',
              __( 'rotateInDownRight', 'fawzi-core' )   => 'rotateInDownRight',
              __( 'rotateInUpLeft', 'fawzi-core' )      => 'rotateInUpLeft',
              __( 'rotateInUpRight', 'fawzi-core' )     => 'rotateInUpRight',
              __( 'rotateOut', 'fawzi-core' )           => 'rotateOut',
              __( 'rotateOutDownLeft', 'fawzi-core' )   => 'rotateOutDownLeft',
              __( 'rotateOutDownRight', 'fawzi-core' )  => 'rotateOutDownRight',
              __( 'rotateOutUpLeft', 'fawzi-core' )     => 'rotateOutUpLeft',
              __( 'rotateOutUpRight', 'fawzi-core' )    => 'rotateOutUpRight',
              __( 'slideInUp', 'fawzi-core' )           => 'slideInUp',
              __( 'slideInDown', 'fawzi-core' )         => 'slideInDown',
              __( 'slideInLeft', 'fawzi-core' )         => 'slideInLeft',
              __( 'slideInRight', 'fawzi-core' )        => 'slideInRight',
              __( 'slideOutUp', 'fawzi-core' )          => 'slideOutUp',
              __( 'slideOutDown', 'fawzi-core' )        => 'slideOutDown',
              __( 'slideOutLeft', 'fawzi-core' )        => 'slideOutLeft',
              __( 'slideOutRight', 'fawzi-core' )       => 'slideOutRight',
              __( 'zoomIn', 'fawzi-core' )              => 'zoomIn',
              __( 'zoomInDown', 'fawzi-core' )          => 'zoomInDown',
              __( 'zoomInLeft', 'fawzi-core' )          => 'zoomInLeft',
              __( 'zoomInRight', 'fawzi-core' )         => 'zoomInRight',
              __( 'zoomInUp', 'fawzi-core' )            => 'zoomInUp',
              __( 'zoomOut', 'fawzi-core' )             => 'zoomOut',
              __( 'zoomOutDown', 'fawzi-core' )         => 'zoomOutDown',
              __( 'zoomOutLeft', 'fawzi-core' )         => 'zoomOutLeft',
              __( 'zoomOutRight', 'fawzi-core' )        => 'zoomOutRight',
              __( 'zoomOutUp', 'fawzi-core' )           => 'zoomOutUp',
              __( 'hinge', 'fawzi-core' )               => 'hinge',
              __( 'jackInTheBox', 'fawzi-core' )        => 'jackInTheBox',
              __( 'rollIn', 'fawzi-core' )              => 'rollIn',
              __( 'rollOut', 'fawzi-core' )             => 'rollOut',
            ),
            'param_name' => 'btwo_animation',
            'description' => __( 'Select your animation.', 'fawzi-core' ),
          ),  
          array(
            'type' => 'textfield',
            'value' => '',
            'heading' => __( 'Custom Class', 'fawzi-core' ),
            'param_name' => 'custom_class',
          ),    
        ),
        
      ),
      fawziLib::vt_class_option(),

      // Style      
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Caption Overlay Color', 'fawzi-core'),
        "param_name"  => "caption_overlay",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Title Color', 'fawzi-core'),
        "param_name"  => "title_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Content Color', 'fawzi-core'),
        "param_name"  => "content_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-4 vc_column vt_field_space',
      ),
      array(
        "type"        => "notice",
        "heading"     => __( "Button One Option", 'fawzi-core' ),
        "param_name"  => 'bone',
        'class'       => 'cs-success',
        'value'       => '',
        "group"       => __('Style', 'fawzi-core'),
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button One Text Color', 'fawzi-core'),
        "param_name"  => "bone_text_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button One Text Hover Color', 'fawzi-core'),
        "param_name"  => "bone_text_hover_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button One Background Color', 'fawzi-core'),
        "param_name"  => "bone_bg_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button One Background Hover Color', 'fawzi-core'),
        "param_name"  => "bone_bg_hover_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button One Border Color', 'fawzi-core'),
        "param_name"  => "bone_border_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button One Border Hover Color', 'fawzi-core'),
        "param_name"  => "bone_border_hover_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        => "notice",
        "heading"     => __( "Button Two Option", 'fawzi-core' ),
        "param_name"  => 'btwo',
        'class'       => 'cs-success',
        'value'       => '',
        "group"       => __('Style', 'fawzi-core'),
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Two Text Color', 'fawzi-core'),
        "param_name"  => "btwo_text_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Two Text Hover Color', 'fawzi-core'),
        "param_name"  => "btwo_text_hover_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Two Background Color', 'fawzi-core'),
        "param_name"  => "btwo_bg_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Two Background Hover Color', 'fawzi-core'),
        "param_name"  => "btwo_bg_hover_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Two Border Color', 'fawzi-core'),
        "param_name"  => "btwo_border_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'colorpicker',
        "heading"     =>__('Button Two Border Hover Color', 'fawzi-core'),
        "param_name"  => "btwo_border_hover_color",
        "value"       => "",
        "group"       => __('Style', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      // Size
      array(
        "type"        =>'textfield',
        "heading"     =>__('Title Text Size', 'fawzi-core'),
        "param_name"  => "title_size",
        "value"       => "",
        "group"       => __('Size', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Content Text Size', 'fawzi-core'),
        "param_name"  => "title_size",
        "value"       => "",
        "group"       => __('Size', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Button One Text Size', 'fawzi-core'),
        "param_name"  => "bone_text_size",
        "value"       => "",
        "group"       => __('Size', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),
      array(
        "type"        =>'textfield',
        "heading"     =>__('Button Two Text Size', 'fawzi-core'),
        "param_name"  => "btwo_text_size",
        "value"       => "",
        "group"       => __('Size', 'fawzi-core'),
        'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
      ),

      ), // Params
    ) );
  }
}