<?php
/**
 * Case Studies - Shortcode Options
 */
add_action( 'init', 'fwzi_case_studies_vc_map' );
if ( ! function_exists( 'fwzi_case_studies_vc_map' ) ) {
  function fwzi_case_studies_vc_map() {
    vc_map( array(
      "name" => __( "Case Studies", 'fawzi-core'),
      "base" => "fwzi_case_studies",
      "description" => __( "Case Studies Styles", 'fawzi-core'),
      "icon" => "fa fa-briefcase color-green",
      "category" => FawziLib::fwzi_cat_name(),
      "params" => array(

        array(
          "type"        =>'textfield',
          "heading"     =>__('Limit', 'fawzi-core'),
          "param_name"  => "case_studies_limit",
          "value"       => "",
          'admin_label' => true,
          "description" => __( "Enter the number of items to show.", 'fawzi-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Column', 'fawzi-core' ),
          'value' => array(
            __( 'Select Case Studies Columns', 'fawzi-core' ) => '',
            __( 'Column Two', 'fawzi-core' ) => 'col-md-6 col-sm-6 col-xs-12',
            __( 'Column Three', 'fawzi-core' ) => 'col-md-4 col-sm-4 col-xs-12',
          ),
          'admin_label' => true,
          'param_name' => 'case_studies_column',
          'description' => __( 'Select your case_studies column.', 'fawzi-core' ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),        

        array(
    			"type"        => "notice",
    			"heading"     => __( "Enable & Disable", 'fawzi-core' ),
    			"param_name"  => 'ends_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),
        array(
          "type"        =>'switcher',
          "heading"     =>__('Filter', 'fawzi-core'),
          "param_name"  => "case_studies_filter",
          "value"       => "",
          "std"         => true,
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        =>'switcher',
          "heading"     =>__('Pagination', 'fawzi-core'),
          "param_name"  => "case_studies_pagination",
          "value"       => "",
          "std"         => true,
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'param_name'      => 'case_studies_pagination_type',
          'type'    => 'dropdown',
          'heading'   => esc_html__('Case Studies Pagination Type', 'fawzi-core'),
          'value'        => array(
            __( 'Select Pagination Type', 'fawzi-core' ) => '',
            __( 'Ajax Infinite Scroll', 'fawzi-core' ) => 'infinite-scroll',
            __( 'Ajax Button', 'fawzi-core' ) => 'load-more',
            __( 'Navigation', 'fawzi-core' ) => 'navigation',
          ),
          'dependency' => array(
            'element' => 'case_studies_pagination',
            'value' => 'true',
          ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Button Text', 'fawzi-core'),
          "param_name"  => "cs_more_btn_text",
          "value"       => "",
          "description" => __( "Enter the button text.", 'fawzi-core'),
          'dependency' => array(
              'element' => 'case_studies_pagination_type',
              'value' => 'load-more',
            ),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'param_name'        => 'cs_load_icon_option',
          'type'      => 'dropdown',
          'value'   => array(
            __( 'Select Load More icon', 'fawzi-core' ) => '',
             __('Ball Scale Multiple', 'fawzi-core') => 'ball-scale-multiple',
             __('Ball Pulse', 'fawzi-core') => 'ball-pulse',
             __('Ball Grid Pulse', 'fawzi-core') => 'ball-grid-pulse',
             __('Ball Clip Rotate', 'fawzi-core') => 'ball-clip-rotate',
             __('Ball Clip Rotate Pulse', 'fawzi-core') => 'ball-clip-rotate-pulse',
             __('Square Spin', 'fawzi-core') => 'square-spin',
             __('Ball Clip Rotate Multiple', 'fawzi-core') => 'ball-clip-rotate-multiple',
             __('Ball Pulse Rise', 'fawzi-core') => 'ball-pulse-rise',
             __('Ball Rotate', 'fawzi-core') => 'ball-rotate',
             __('Cube Transition', 'fawzi-core') => 'cube-transition',
             __('Ball Zig Zag', 'fawzi-core') => 'ball-zig-zag',
             __('Ball Zig Zag Deflect', 'fawzi-core') => 'ball-zig-zag-deflect',
             __('Ball Triangle Path', 'fawzi-core') => 'ball-triangle-path',
             __('Ball Scale', 'fawzi-core') => 'ball-scale',
             __('Line Scale', 'fawzi-core') => 'line-scale',
             __('Line Scale Party', 'fawzi-core') => 'line-scale-party',
             __('Ball Pulse Sync', 'fawzi-core') => 'ball-pulse-sync',
             __('Ball Beat', 'fawzi-core') => 'ball-beat',
             __('Line Scale Pulse Out', 'fawzi-core') => 'line-scale-pulse-out',
             __('Line Scale Pulse Out Rapid', 'fawzi-core') => 'line-scale-pulse-out-rapid',
             __('Ball Scale Ripple', 'fawzi-core') => 'ball-scale-ripple',
             __('Ball Scale Ripple Multiple', 'fawzi-core') => 'ball-scale-ripple-multiple',
             __('Ball Spin Fade Loader', 'fawzi-core') => 'ball-spin-fade-loader',
             __('Line Spin Fade Loader', 'fawzi-core') => 'line-spin-fade-loader',
             __('Triangle Skew Spin', 'fawzi-core') => 'triangle-skew-spin',
             __('Pacman', 'fawzi-core') => 'pacman',
             __('Ball Grid Beat', 'fawzi-core') => 'ball-grid-beat',
             __('Semi Circle Spin', 'fawzi-core') => 'semi-circle-spin',
          ),
          'dependency' => array(
              'element' => 'case_studies_pagination_type',
              'value' => 'infinite-scroll',
            ),
          'heading'     => esc_html__('Loader Icon Style', 'fawzi-core'),
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
    			"type"        => "notice",
    			"heading"     => __( "Listing", 'fawzi-core' ),
    			"param_name"  => 'lsng_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
    		),        
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order', 'fawzi-core' ),
          'value' => array(
            __( 'Select Case Studies Order', 'fawzi-core' ) => '',
            __('Asending', 'fawzi-core') => 'ASC',
            __('Desending', 'fawzi-core') => 'DESC',
          ),
          'param_name' => 'case_studies_order',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          'type' => 'dropdown',
          'heading' => __( 'Order By', 'fawzi-core' ),
          'value' => array(
            __('None', 'fawzi-core') => 'none',
            __('ID', 'fawzi-core') => 'ID',
            __('Author', 'fawzi-core') => 'author',
            __('Title', 'fawzi-core') => 'title',
            __('Date', 'fawzi-core') => 'date',
          ),
          'param_name' => 'case_studies_orderby',
          'edit_field_class'   => 'vc_col-md-6 vc_column vt_field_space',
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Show only certain categories?', 'fawzi-core'),
          "param_name"  => "case_studies_show_category",
          "value"       => "",
          "description" => __( "Enter category SLUGS (comma separated) you want to display.", 'fawzi-core')
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Miss-Aligned?', 'fawzi-core'),
          "param_name"  => "case_studies_min_height",
          "value"       => "",
          "description" => __( "Enter minimum height value in px.", 'fawzi-core'),
        ),
        FawziLib::vt_class_option(),

        // Stylings
        array(
    			"type"        => "notice",
    			"heading"     => __( "Filter", 'fawzi-core' ),
    			"param_name"  => 'flst_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
          "group"       => __('Style', 'fawzi-core'),
    		),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Color', 'fawzi-core'),
          "param_name"  => "filter_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
          'dependency' => array(
            'element' => 'case_studies_filter',
            'value' => 'true',
          ),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Active Color', 'fawzi-core'),
          "param_name"  => "filter_active_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
          'dependency' => array(
            'element' => 'case_studies_filter',
            'value' => 'true',
          ),
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Text Size', 'fawzi-core'),
          "param_name"  => "filter_size",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
          "description" => __( "Enter filter text size.", 'fawzi-core'),
          'dependency' => array(
            'element' => 'case_studies_filter',
            'value' => 'true',
          ),
        ),
        // Padding
        array(
          "type"        => "notice",
          "heading"     => __( "Column Padding", 'fawzi-core' ),
          "param_name"  => 'pad_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Top', 'fawzi-core'),
          "param_name"  => "pad_top",
          "value"       => "",
          "group"       => __('Style', 'fawzi-core'),
          'admin_label' => true,
          "description" => __( "Enter the top space value.", 'fawzi-core'),
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Right', 'fawzi-core'),
          "param_name"  => "pad_right",
          "value"       => "",
          "group"       => __('Style', 'fawzi-core'),
          'admin_label' => true,
          "description" => __( "Enter the right space value.", 'fawzi-core'),
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Bottom', 'fawzi-core'),
          "param_name"  => "pad_bottom",
          "value"       => "",
          "group"       => __('Style', 'fawzi-core'),
          'admin_label' => true,
          "description" => __( "Enter the bottom space value.", 'fawzi-core'),
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),
        array(
          "type"        =>'textfield',
          "heading"     =>__('Left', 'fawzi-core'),
          "param_name"  => "pad_left",
          "value"       => "",
          "group"       => __('Style', 'fawzi-core'),
          'admin_label' => true,
          "description" => __( "Enter the left space value.", 'fawzi-core'),
          'edit_field_class'   => 'vc_col-md-3 vc_column vt_field_space',
        ),

        // Size
        array(
    			"type"        => "notice",
    			"heading"     => __( "Item Style", 'fawzi-core' ),
    			"param_name"  => 'itm_opt',
    			'class'       => 'cs-warning',
    			'value'       => '',
          "group"       => __('Style', 'fawzi-core'),
    		),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Image Overlay Color', 'fawzi-core'),
          "param_name"  => "image_overlay_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Icon Color', 'fawzi-core'),
          "param_name"  => "icon_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Icon Hover Color', 'fawzi-core'),
          "param_name"  => "icon_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Icon Background Color', 'fawzi-core'),
          "param_name"  => "icon_bg_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Icon Background Hover Color', 'fawzi-core'),
          "param_name"  => "icon_bg_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        => 'textfield',
          "heading"     => __('Title Size', 'fawzi-core'),
          "param_name"  => "case_studies_title_size",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Title Color', 'fawzi-core'),
          "param_name"  => "case_studies_title_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Title Hover Color', 'fawzi-core'),
          "param_name"  => "case_studies_title_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),    
        array(
          "type"        => "notice",
          "heading"     => __( "Button Style", 'fawzi-core' ),
          "param_name"  => 'btn_opt',
          'class'       => 'cs-warning',
          'value'       => '',
          "group"       => __('Style', 'fawzi-core'),
        ),  
        array(
          "type"        => 'textfield',
          "heading"     => __('Button Top Space', 'fawzi-core'),
          "param_name"  => "btn_top_space",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),  
        array(
          "type"        => 'textfield',
          "heading"     => __('Button Bottom Space', 'fawzi-core'),
          "param_name"  => "btn_bottom_space",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Button BG Color', 'fawzi-core'),
          "param_name"  => "btn_bg_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Button Text Color', 'fawzi-core'),
          "param_name"  => "btn_text_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Button Border Color', 'fawzi-core'),
          "param_name"  => "btn_border_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Button BG Hover Color', 'fawzi-core'),
          "param_name"  => "btn_bg_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Button Text Hover Color', 'fawzi-core'),
          "param_name"  => "btn_text_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),
        array(
          "type"        => 'colorpicker',
          "heading"     => __('Button Border Hover Color', 'fawzi-core'),
          "param_name"  => "btn_border_hover_color",
          "value"       => "",
          'edit_field_class'   => 'vc_col-md-4 vt_field_space',
          "group"       => __('Style', 'fawzi-core'),          
        ),
        
      )
    ) );
  }
}
